bmaquiosque.username=${BMAQUIOSQUE_USERNAME:}
bmaquiosque.password=${BMAQUIOSQUE_PASSWORD:}
bmaquiosque.max-entry-time=${BMAQUIOSQUE_MAX_ENTRY_TIME:}
bmaquiosque.jitter-minutes=${BMAQUIOSQUE_JITTER_MINUTES:}
bmaquiosque.timezone=${BMAQUIOSQUE_TIMEZONE:America/Sao_Paulo}
