bmaquiosque.username=${BMAQUIOSQUE_USERNAME:user.test}
bmaquiosque.password=${BMAQUIOSQUE_PASSWORD:pass.test}
bmaquiosque.max-entry-time=${BMAQUIOSQUE_MAX_ENTRY_TIME:09:00}
bmaquiosque.jitter-minutes=${BMAQUIOSQUE_JITTER_MINUTES:0}
bmaquiosque.timezone=${BMAQUIOSQUE_TIMEZONE:America/Sao_Paulo}
bmaquiosque.url=${BMAQUIOSQUE_URL:http://localhost:8080/wpe/quiosque/}
bmaquiosque.selectors.username=${BMAQUIOSQUE_SELECTORS_USERNAME:#Usuario}
bmaquiosque.selectors.password=${BMAQUIOSQUE_SELECTORS_PASSWORD:#Senha}
bmaquiosque.selectors.login-button=${BMAQUIOSQUE_SELECTORS_LOGIN_BUTTON:input[type='submit']}
bmaquiosque.selectors.markings-container=${BMAQUIOSQUE_SELECTORS_MARKINGS_CONTAINER:.marking-time-item}
bmaquiosque.selectors.punch-button=${BMAQUIOSQUE_SELECTORS_PUNCH_BUTTON:#btn-punch}

discord.bot.enabled=${DISCORD_BOT_ENABLED:false}
discord.bot.token=${DISCORD_BOT_TOKEN:}
discord.bot.guild-id=${DISCORD_BOT_GUILD_ID:}

